<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type Rate_rtespc</name>
   <tag></tag>
   <elementGuidId>57bda6b0-646d-4098-b09a-0f1628433748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rte-emx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rte-emx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rate EMX&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>133449ee-91f1-46a7-bae0-ff988ff28560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>af0b253d-cb2f-41e7-861a-b27027daf645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rtespc</value>
      <webElementGuid>8ed446f1-ed7d-4092-93d1-ced1a38c45ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>rtespc</value>
      <webElementGuid>5e313d5f-0c11-4a27-a256-b7d13272c75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rte-emx</value>
      <webElementGuid>201589b8-dd4f-4a62-bae4-d1ae8648034a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rteEMX</value>
      <webElementGuid>db3eb787-4656-4290-9fe0-33a143eeb12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>19b810f7-514d-4a84-8278-dd8e6a6277c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db48dfe7-bae0-453e-9744-0a64958491dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rte-emx&quot;)</value>
      <webElementGuid>656759f3-46a3-42d4-9ce3-635adbb1da58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rte-emx']</value>
      <webElementGuid>10eb3089-4181-4599-85d1-3f0a1883210c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>0f690bfc-5e8a-4b70-8da3-0b65e6aa9251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>2d7e20cb-d263-4cfa-a8c7-c4e02b685a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rtespc' and @id = 'rte-emx']</value>
      <webElementGuid>765326c8-8333-44d3-ab58-64f4fdefe865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
