<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_form-control form-control-sm</name>
   <tag></tag>
   <elementGuidId>83a66b18-b3ee-46a2-a029-992b9827c9c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.align-items-center.remarks2 > div.col > textarea.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fast-tran']/div/div[6]/div[2]/div/div/div[12]/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fast-tran textarea >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6e2cd59c-5c61-4390-89a1-124aefee4030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>4c79f558-a015-4f86-b9d6-18501cae1fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f0542f93-4bbe-41f2-839d-4c58ba5997d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wt-ignore-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a69608b-1dd6-4aee-8248-dfa2e8afe9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>74a45137-0dd0-4fc1-baeb-57238689c65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a001dca3-f0b9-411c-b33d-eadbd298c5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;feeder-html&quot;]/div[@class=&quot;fast-body form-field-trx&quot;]/div[@class=&quot;row align-items-center remarks2&quot;]/div[@class=&quot;col&quot;]/textarea[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>7a380903-8bb6-43a2-901d-911dfa48c507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[6]/div[2]/div/div/div[12]/div[2]/textarea</value>
      <webElementGuid>c3187b30-454b-4ad7-81c4-727a2534da51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/textarea</value>
      <webElementGuid>c5d51492-e4d2-4763-ba2d-cacd35c55380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
