<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02. Input-No ID</name>
   <tag></tag>
   <elementGuidId>68d4234e-53d2-4207-a3d8-9425ccec3ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.mb-2 > div.col > div.input-group.input-group-sm > input.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[237]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card-body > div:nth-child(2) > div:nth-child(2) > .input-group > input >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee702f13-9bae-4f86-9ad5-2c09f02c36d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bc16c79-78b6-46f9-b099-951b72e5ffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>no_id_pelaku</value>
      <webElementGuid>307407fc-3d7e-4448-a29c-79b71d7d9e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>var%20prev%20=%20json%5B%22prev_val%22%5D;%0Avar%20now%20=%20json%5B%22no_id_pelaku%22%5D;%0Aif($(me).val().length%20%3E%200%20&amp;&amp;%20now%20!=%20prev)%20fast.tranInquiry();</value>
      <webElementGuid>789924f1-3951-460b-92ff-c02fb6ab028a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>362f2bdb-2e2d-465b-a515-c36af977db3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>d3931a85-837f-4d29-a3c0-9cff42280581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d84641f7-bf6a-44f2-b6db-316139f3b473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body&quot;]/div[@class=&quot;feeder-html&quot;]/div[@class=&quot;fast-body form-input-pelaku&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group input-group-sm&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>1a78487e-1590-43a0-b47f-edeb1cbd35c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[237]</value>
      <webElementGuid>94997ad5-7abf-4281-9705-fecd0595a1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[3]/div/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>956b2a1b-7889-4990-a7c2-a68d48be9165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>d1dd5e57-8dd4-43cb-8698-b048cc2b5cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f77e11b5-7adb-491e-bb87-fa78e642bad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
