<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02. Option-Type Rate</name>
   <tag></tag>
   <elementGuidId>4f7fe00b-2345-4c52-b04e-9642c53e8915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rte-emx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rte-emx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rate EMX&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd05d273-f151-43ca-8627-445fe45b7a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>84ee4e79-cff8-4e09-aa88-88155ef8f5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rtespc</value>
      <webElementGuid>9a29e739-d441-4d17-9888-1cdc96195638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>rtespc</value>
      <webElementGuid>58e6e5fb-b6ff-41e1-9bcc-cfcda9c1e997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rte-emx</value>
      <webElementGuid>f6557807-1206-422e-854a-df7ec4ffa493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rteEMX</value>
      <webElementGuid>ee441116-52e7-4fe8-8dd8-ac056325fec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>62a98019-3d0e-4969-b83e-66f05305794b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5fbb02c3-fd4c-4082-94b0-c5186cde0f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rte-emx&quot;)</value>
      <webElementGuid>6479fa0e-74b9-4b2b-8688-343d3931f001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rte-emx']</value>
      <webElementGuid>67242fb5-8f58-407f-87a3-cbe11a12aacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>f6eed9f2-26ae-4b5a-915c-023bdf8cb5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>bd82b5d2-0a5a-46cf-a43f-db093ea3d291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rtespc' and @id = 'rte-emx']</value>
      <webElementGuid>155b6105-591e-4563-a5da-3d445f857d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
