<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type Rate_rtespc</name>
   <tag></tag>
   <elementGuidId>1193467e-a252-4c09-a03f-317337727f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rte-emx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rte-emx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rate EMX&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27854f8c-26e9-4746-9092-150c7d4c11bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e94cf67b-aa0d-4ffe-96a5-19ba9abbd25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rtespc</value>
      <webElementGuid>c59f5df4-cf91-4076-ab48-f11e23618fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>rtespc</value>
      <webElementGuid>c92b301e-4fd1-4c6f-a20b-54701b3931b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rte-emx</value>
      <webElementGuid>dc1f16a1-cc38-4e0e-8c58-272390981588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rteEMX</value>
      <webElementGuid>80663506-e07d-4410-abad-c70692307714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>18c68bc7-420d-449f-8408-2b87e795de30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b4868e82-4e47-44f0-9063-867e881cb165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rte-emx&quot;)</value>
      <webElementGuid>0840363b-9768-4927-9c61-a0a3dc93ff13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rte-emx']</value>
      <webElementGuid>acdf20d8-56c2-46c3-9a35-d9bfb1211f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[9]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>2153ebf3-e63b-4dac-96c9-c0b88ff219c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[9]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>0f5975f5-5fe9-4be8-8e58-3b37cb05730a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'rtespc' and @id = 'rte-emx']</value>
      <webElementGuid>f0d79409-dc8c-4394-97e6-948c2ce39608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
