<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal yang didebet dari Rekening_amount_1</name>
   <tag></tag>
   <elementGuidId>267fc4fd-c18a-443f-badc-a92f184e4cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#amount_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bff5ea1d-2382-4788-80af-373ea7c3fe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_1</value>
      <webElementGuid>d1590692-0668-4ba8-9d71-a97be5a05051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc18c07d-15c8-4cda-a3d8-f4b8dde4f5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount1</value>
      <webElementGuid>ca2be387-4b62-4e0e-8fc6-5487cfb58fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'bawah');</value>
      <webElementGuid>1307ee92-7047-405f-90cc-fb0f3036795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d439cb97-7ace-47c0-826d-8b2b29f0eee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json-dup</name>
      <type>Main</type>
      <value>udl_amount</value>
      <webElementGuid>26f348d9-7715-4a8e-820d-5918d97c877b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt1</value>
      <webElementGuid>e2168ab6-7f27-44cb-acb7-4ad2ec5f297a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>598a6c27-3a5e-446e-936e-763121252ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7355f9cf-80aa-4c9b-8856-f51219197b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_1&quot;)</value>
      <webElementGuid>e6f3d88e-9b94-428f-97b7-2d109ba231ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_1']</value>
      <webElementGuid>de5ce1a9-920f-490b-8eb4-1dbbf1e03a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[10]/div[2]/div/div/div[13]/div[2]/div/input</value>
      <webElementGuid>ddc1455d-a536-4fec-8096-4a06cac0ce5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/div[13]/div[2]/div/input</value>
      <webElementGuid>3819f1a4-fb3b-4772-a7ed-a9d604343d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount_1' and @type = 'text']</value>
      <webElementGuid>94871281-48fc-4055-9cda-1801babfbef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
