<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. ID  Jenis ID  Jenis Pelaku_form-c_6c50d4</name>
   <tag></tag>
   <elementGuidId>ca739c86-42d7-4a80-a1c9-04ae025cebd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.mb-2 > div.col > div.input-group.input-group-sm > input.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[237]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card-body > div:nth-child(2) > div:nth-child(2) > .input-group > input >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81c09e14-30e2-43ef-ad26-c3ef421d9353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a2719c1-9812-4afd-948f-10ccf6522236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>no_id_pelaku</value>
      <webElementGuid>93281396-65e3-4b20-bafc-eeda5fbd8e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>var%20prev%20=%20json%5B%22prev_val%22%5D;%0Avar%20now%20=%20json%5B%22no_id_pelaku%22%5D;%0Aif($(me).val().length%20%3E%200%20&amp;&amp;%20now%20!=%20prev)%20fast.tranInquiry();</value>
      <webElementGuid>1ed96ec8-06ca-4b7b-9643-cba1738b435a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cef4b4b1-88ec-42c8-bf52-8a18ebb817a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>00285737-045a-485e-9304-fc3a5b00703f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>604d03e4-972b-46bf-a498-44170fde04d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body&quot;]/div[@class=&quot;feeder-html&quot;]/div[@class=&quot;fast-body form-input-pelaku&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group input-group-sm&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>9e71e00e-66f8-4e8a-9373-83b0b8cba4b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[237]</value>
      <webElementGuid>cc2a0b4f-c285-4e40-a56d-084dbe3e2738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[6]/div/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>aa1c5bb6-3943-45ff-84d1-57c6379e1f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>09be5c14-d8ab-45ac-8975-69e10e5ddf09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>ef05b21e-1df9-40b1-9b16-71cbb2500adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
