<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Tunai yang ditarik_amount_2</name>
   <tag></tag>
   <elementGuidId>11fc98bf-f15d-481a-80bb-d8fa35d2957e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#amount_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2da413f1-1e60-46bd-b83e-d84020128bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_2</value>
      <webElementGuid>96cf35b1-bbaf-4c0b-bc63-d4cc2d8da882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddcd3452-846c-423d-bc98-0f34148b6e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount2</value>
      <webElementGuid>4492ee8d-bf3c-4075-9072-11a5207397e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'atas')%0A//provisionFee%20func%20di%20remittance%0A/*try%20%7BprovisionFee(json);%7D%0Acatch(err)%20%7BcalcAmount(json,'atas');%7D*/</value>
      <webElementGuid>7197ce68-b1a1-4a91-a5a9-6d60e4a7cd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7df582e4-599e-4ff2-acc0-735ae4d4d2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt2</value>
      <webElementGuid>42b41a7c-c888-4a31-8a34-a1314c802de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>3ccdd367-c26e-44e2-8189-43f0a0cbe432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>511c0647-ce5a-45b4-9954-696294696d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_2&quot;)</value>
      <webElementGuid>d85ec90d-a078-4e79-9074-b80c082bcba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_2']</value>
      <webElementGuid>8b386c43-d2bf-4067-88f6-4a6ee6167008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[10]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>b535168f-0a8d-4695-abdc-50d3efb7fd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>2b403c17-afa0-4a11-8d0e-cd050dda513b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount_2' and @type = 'text']</value>
      <webElementGuid>0c607eab-6dbb-4f9e-b487-a95ede46efb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
